# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('intro', models.CharField(max_length=150, null=True)),
                ('content', models.CharField(max_length=20000)),
                ('time', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20, null=True)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
    ]
